### ISSUE TITLE
standardize in-program currency

### ISSUE THREAD

**Issue by j1nxie** [j1nxie/python-project#37]
this is a problem since we've never really talked about what currency we're dealing with. numbers from the different models involving money has been very wild, we need to propose one currency and follow through with that currency.

**Comment by R1verrrr** [comment]
I think the currency should be USD, welp its easy to calculating

**Comment by Peachy72** [comment]
Agreed.

**Comment by j1nxie** [comment]
guess we're looking at it as USD now. check ur numbers to see if they make sense - probably aligning them with US wages would be good.
