### ISSUE TITLE
GUI + TUI feature tracker

### ISSUE THREAD

**Issue by j1nxie** [j1nxie/python-project#44]
feature | text-based TUI | tkinter GUI
-------- | ------------ | -----------------
employee management | ✔️ |✔️ 
benefits management |  ✔️ | ✔️ 
attendance management | ✔️ | ✔️ 
payroll management | ✔️ | ✔️ 
department management | ✔️ | ✔️ 
performance management | ✔️ | ✔️ 
login system | ✔️ | ✔️

i wish for feature parity between the two frontends. please make more issues if u want more features for either of these frontends, and mention them in the comments below.

**Comment by j1nxie** [comment]
@menhhduc what did #45 add for the GUI? i want a rundown on the new features outside of just "update", thanks

**Comment by Delnegend** [comment]
Here's a more detailed version of the TUI, double check if there's anything missing from the GUI.

| Menu       | -   | Admin                    | Employee                 |
|------------|-----|--------------------------|--------------------------|
| Attendance | [1] | Check                    | Check                    |
|            | [2] | Update                   | Get report               |
|            | [3] | Get report               | Back                     |
|            | [4] | Back                     |                          |
|            |     |                          |                          |
| Benefit    | [1] | Add                      | View details of one      |
|            | [2] | Apply one to employee    | List all                 |
|            | [3] | Remove                   | Request to enroll in one |
|            | [4] | Update                   | Back                     |
|            | [5] | View details of one      |                          |
|            | [6] | List all                 |                          |
|            | [7] | Request to enroll in one |                          |
|            | [8] | Resolve pending requests |                          |
|            | [9] | Back                     |                          |
|            |     |                          |                          |
| Department | [1] | Add                      | View details of one      |
|            | [2] | Remove                   | List all                 |
|            | [3] | Update information for   | Back                     |
|            |     | one                      |                          |
|            | [4] | Add employee to one      |                          |
|            | [5] | Remove employee from one |                          |
|            | [6] | View details of one      |                          |
|            | [7] | List all                 |                          |
|            | [8] | List employees does not  |                          |
|            |     | belong to any department |                          |
|            | [9] | Back                     |                          |
|            |     |                          |                          |
| Employee   | [1] | Add                      | View details             |
|            | [2] | Remove                   | Change password          |
|            | [3] | Update information       | Back                     |
|            | [4] | View details of one      |                          |
|            | [5] | List all                 |                          |
|            | [6] | Change password          |                          |
|            | [7] | Back                     |                          |
|            |     |                          |                          |
| Payroll    | [1] | Create                   | View details             |
|            | [2] | Update                   | Back                     |
|            | [3] | View all                 |                          |
|            | [4] | Back                     |                          |

**Comment by j1nxie** [comment]
pinging GUIs: @menhhduc @Peachy72 @R1verrrr 

would be good to take a look at this

**Comment by Delnegend** [comment]
Add grant/revoke admin in the MenuEmpl of admin.

@menhhduc @Peachy72 @R1verrrr
Before the logged in admin MODIFY ANYTHING, check if they have the permission to do so by calling `<company_obj>.can_modify(<type_of_data>, <the_employee_they're_going_to_modify>)`, no need to use `<employee_obj>.is_admin` or `<company_obj>.is_owner`

The only thing the employee can modify from the DB is set their attendance of that day to True, everything else, they can only read what's belong/assigned to them, except benefit plans since they need to see what's there to request apply to.
