### ISSUE TITLE
bug: crash while getting attendance report

### ISSUE THREAD

**Issue by j1nxie** [j1nxie/python-project#51]
bug report from @menhhduc 

![image](https://user-images.githubusercontent.com/52886388/230783802-36131c9b-599e-4134-b65e-bc15ef1b4842.png)

reproduction methods:
1. add a department
2. add an employee
3. check attendance for that employee
4. get attendance report

@Delnegend should take a look at this and see what's happening

**Comment by Delnegend** [comment]
I forgot to return the list in `get_available_years()` in the `Attendance` model.
